CREATE DATABASE IF NOT EXISTS codeup_test_db;
USE codeup_test_db;

CREATE TABLE IF NOT EXISTS albums (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    artist VARCHAR(100) DEFAULT 'UNKNOWN',
    name VARCHAR(100) DEFAULT 'UNKNOWN',
    release_date INT NOT NULL,
    sales FLOAT NOT NULL,
    genre VARCHAR(50) DEFAULT 'NONE',
    PRIMARY KEY(id)
);

SELECT * FROM albums;